Product_Rating/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RatingApp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

RatingApp/urls.py
from django.urls import path

from . import views
from .views import *

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('About/', views.AboutPage, name='about'),
    path('products/', ProductPage.as_view(), name='products'),
    path('products/<p_slug>-details/', views.ProductDetailsPage, name='product-details'),

    path('auth/Register/', views.regView, name='register'),
    path('auth/login/', views.loginView, name='login'),
    path('auth/logout/', views.logoutView, name='logout')
]

RatingApp/models.py
from django.db import models
from django.db.models.fields import CharField, DateField, EmailField, IntegerField, SlugField, TextField
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ForeignKey
from django.urls import reverse
from datetime import datetime

from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

CATEGORY_CHOICES = (
    ('Technical', 'Technical'),
    ('Consumable','Consumable'),
    ('Sports','Sports'),
    ('Fashion','Fashion')
)

class Product(models.Model):
    slug = models.SlugField()
    p_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    description = models.TextField(max_length=250)
    image = models.ImageField(upload_to='media')

    def __str__(self):
        return self.p_name

    def get_absolute_url(self):
        return reverse('product-details', kwargs={'p_slug':self.slug})

    @property
    def productReview(self):
        return self.review_set.all()


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    user = models.CharField(max_length=50)
    user_email = models.EmailField()
    rate = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    review = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'On {}, By {}'.format(str(self.product), self.user)

    def get_absolute_url(self):
        return reverse('product-details')

RatingApp/forms.py
from RatingApp.models import Review
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class RegForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
        }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['product','user','user_email','rate','review']

        

RatingApp/views.py
from django.forms.models import ALL_FIELDS
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.views.generic import ListView
from django.db.models import Avg
# from django.contrib.auth.decorators import login_required

from .models import *
from .forms import RegForm, ReviewForm



def HomePage(request):
    context = {}
    return render(request, 'home.html', context)

def AboutPage(request):
    context = {}
    return render(request, 'about.html', context)

class ProductPage(ListView):
    model = Product
    template_name = 'ratingTemplates/products.html'


def ProductDetailsPage(request, p_slug):
    selected_product = get_object_or_404(Product, slug=p_slug)
    

    review_form = ReviewForm()
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            if selected_product.productReview.filter(user=request.user).exists():
                messages.info(request, 'You Can Only Review Once...')
            else:
                review_form.save()
                messages.success(request, 'Your Review was Submited successfully')
        else:
            messages.warning(request, 'Failed to submit')

    # get average rating
    avgRate  = Review.objects.filter(product=selected_product).aggregate(Avg('rate'))

    context = {'selected_product':selected_product, 'review_form':review_form, 'avgRate':avgRate}
    return render(request, 'ratingTemplates/product-details.html', context)


def regView(request):
    form = RegForm()
    if request.method == "POST":
        form = RegForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, "You've successfully registered as "+ username +", you can now login")
            return redirect('login')
    
    context = {'form':form}
    return render(request, 'ratingTemplates/register.html', context)

def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('products')
        else:
            messages.error(request, 'Invalid Username or Password')

    context = {}
    return render(request, 'ratingTemplates/login.html', context)

def logoutView(request):
    logout(request)
    return redirect('home')

RatingApp/templates/about.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- favicon -->
     <link rel='icon' href="{% static 'images/rate-us.png' %}" type='image/x-icon'>

     <!-- static css -->
     <link rel="stylesheet" href="{% static 'style/homestyle.css' %}">
 
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
     
    <title>Product Rating</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand" href="#">
        <img src="{% static 'images/rate-us.png' %}" alt="rate us logo" style="height:60px;width:200%;" >
      </span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-auto justify-content-center">
          <form class="form-inline my-2 my-lg-0 ">
              <input class="form-control mr-sm-2" type="search" placeholder="Search for products" aria-label="Search">
              <button class="btn btn-warning my-2 my-sm-0" type="submit">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                      <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                  </svg>
              </button>
          </form>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'products' %}">Products <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">About Us <span class="sr-only">(current)</span></a>
          </li>
          
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">
              {{request.user.username}}, Logout
              <svg class="bi bi-box-arrow-in-right" width="24" height="24" viewBox="0 0 20 20" fill="white" title='Log in' xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
              </svg>
            </a>
          </li>
            {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'login' %}">
              Login
              <svg class="bi bi-box-arrow-in-right" width="24" height="24" viewBox="0 0 20 20" fill="white" title='Log in' xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
              </svg>
            </a>
          </li>
          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>

  <section class="home__mainBody">
    <div class="row">
      <div class="col-sm-6">
        <div class="container">
          <img src="{% static 'images/rate-us.png' %}" alt="" width="90%" height="350em">
        </div>
      </div>

      <div class="col-sm-4 text-light" style="background: #4b5469">
        <div class="container pt-3">
          <h2>About Rate us Site</h2>
          <blockquote>
            Here we welcome your Ratings and Raviews on our products. Here we welcome your Ratings and Raviews on our products. Here we welcome your Ratings and Raviews on our products
          </blockquote>
          <!-- <p>
            <a href="{% url 'products' %}" class='btn btn-warning m-2' >View Products</a> 
            <a href="{% url 'about' %}" class='btn btn-warning m-2' >About Us</a> 
            <a href="" class='btn btn-warning m-2' >Login</a>
          </p> -->
        </div>
      </div>
    </div>
  </section> 
  
  <section class="contact">
      <div class="container">
        <h1 class="text-primary">Contact Us Via</h1>
        <table>
            <tr>
                <td><a href="" style="text-decoration:none;"><img src="{% static 'images/f.png' %}" style="width:50px; height:50px" alt="facebook">Facebook</a> </td>
                <td><a href="" style="text-decoration:none;"><img src="{% static 'images/t.png' %}" style="width:50px; height:50px" alt="twitter">Twitter</a></td>
                <td><a href="" style="text-decoration:none;"><img src="{% static 'images/mail.png' %}" style="width:50px; height:50px" alt="mail">Email</a> </td>
            </tr>
            <tr>
                <td><a href="" style="text-decoration:none;"><img src="{% static 'images/i.png' %}" style="width:50px; height:50px" alt="instagram">Instagram</a></td>
            </tr>
        </table>
      </div>
  </section>
  
  <br>

  <footer class="footer text-center pt-3 pb-3 text-light"  style="background: #4b5469">
    <h4>
      CopyRight Rate US &copy 2020
    </h4>
  </footer>

</body>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

RatingApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- favicon -->
     <link rel='icon' href="{% static 'images/rate-us.png' %}" type='image/x-icon'>

     <!-- static css -->
     <link rel="stylesheet" href="{% static 'style/homestyle.css' %}">

     <!-- static js -->
     <script src="{% static 'js/rating.js' %}"></script>

     <!-- font awesome css -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
     
    <title>Product Rating</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <span class="navbar-brand" href="#">
        <img src="{% static 'images/rate-us.png' %}" alt="rate us logo" style="height:60px;width:200%;" >
      </span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-auto justify-content-center">
          <form class="form-inline my-2 my-lg-0 ">
              <input class="form-control mr-sm-2" type="search" placeholder="Search for products" aria-label="Search">
              <button class="btn btn-warning my-2 my-sm-0" type="submit">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                      <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                  </svg>
              </button>
          </form>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link k" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'products' %}">Products <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">About Us<span class="sr-only">(current)</span></a>
          </li>
          
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">
              {{request.user.username}}, Logout
              <svg class="bi bi-box-arrow-in-right" width="24" height="24" viewBox="0 0 20 20" fill="white" title='Log in' xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
              </svg>
            </a>
          </li>
            {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'login' %}">
              Login
              <svg class="bi bi-box-arrow-in-right" width="24" height="24" viewBox="0 0 20 20" fill="white" title='Log in' xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
              </svg>
            </a>
          </li>
          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>


  <section class="main_body" style="height:40em">
    <div class="row" style="height:100%">
      <div class="col-sm-2 bg-light text-dark table-bordered p-0 m-0">
        {% block sidebar %}

        {% endblock %}
      </div>
      <div class="col-sm-9">
        <div class="container">
          {% block content %}

          {% endblock %}
        </div>
      </div>
    </div>
  </section>
  <br>
  <!-- <footer class="footer text-center pt-3 pb-3 text-light"  style="background: #4b5469">
    <h4>
      CopyRight Rate US &copy 2020
    </h4>
  </footer> -->

</body>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</html>

RatingApp/templates/ratingTemplates/product-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="mt-3 mb-3 container">
    <div class="row mb-4">
        <div class="col-sm-3" style="" >
            <center><img src="{{selected_product.image.url}}" alt="" width='100%' height='250em'></center>
        </div>

        <div class="col-sm-1"></div>

        <div class="col-sm-8 " style="">
            <h4 class="alert alert-warning m-0">Product Details</h4>
            <h5 style="font-weight: bold; text-align: justify;">
                <table class="table-borderless mt-3">
                    <tr><td class="pr-3 pl-3">Product Name:</td><td><small>{{selected_product.p_name}}</small></td></tr>
                    <tr><td colspan='6'><hr></td></tr>
                    <tr><td class="pr-3 pl-3">Category:</td><td colspan='4'><small>{{selected_product.category}}</small></td></tr>
                    <tr><td colspan='6'><hr></td></tr>
                    <tr>
                        <td class="pr-3 pl-3">Overall Rating:</td>
                        <td class="pr-3">
                            <small>
                                <span class="colored fa fa-star{% if avgRate.rate__avg < 1 %}-o empty {% endif %} "></span>
                                <span class="colored fa fa-star{% if avgRate.rate__avg == 1.5 %}-half {% elif avgRate.rate__avg < 2 %}-o empty {% endif %} "></span>
                                <span class="colored fa fa-star{% if avgRate.rate__avg == 2.5 %}-half {% elif avgRate.rate__avg < 3 %}-o empty {% endif %} "></span>
                                <span class="colored fa fa-star{% if avgRate.rate__avg == 3.5 %}-half {% elif avgRate.rate__avg < 4 %}-o empty {% endif %} "></span>
                                <span class="colored fa fa-star{% if avgRate.rate__avg == 4.5 %}-half {% elif avgRate.rate__avg < 5 %}-o empty {% endif %} "></span>
                                <!-- ({{ avgRate.rate__avg }}) -->
                            </small> 
                        </td>
                        <td class='pr-3'></td>
                        <td class='pr-3'>Review Count: </td>
                        <td><small>{{ selected_product.productReview.count }} review(s)</small></td></tr>
                    <tr><td colspan='6'><hr></td></tr>
                    <!-- <tr><td class="pr-3 pl-3">Description:</td><td><small>{{selected_product.description}}</small></td></tr> -->
                </table>
            </h5>

        </div>
    </div>
    <br>

    <ul class="nav nav-tabs" id="myTab" role="tablist" >
        <li  class="nav-item" role="presentation">
            <a class="nav-link" id="details-tab" data-toggle="tab" href="#details" role="tab" aria-controls="details" aria-selected="false">Details</a>
        </li>
        <li  class="nav-item" role="presentation">
            <a class="nav-link active" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="true">Reviews</a>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent" >
        <div class="tab-pane fade" id="details" role="tabpanel" aria-labelledby="details-tab">
            <h2>Product Description:</h2>
            <p>{{selected_product.description}}</p> 
        </div>

        <div class="tab-pane fade show active" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
            <div class="row">
                <div class="col-sm-12 pt-2" >
                    <div class="row pt-2">
                        <div class="col-sm-7"> 
                            <!-- <h4  class="text-dark" style="width:90%">Reviews</h4> -->
                            {% for review in selected_product.productReview %}
                            <div class="card p-2 mb-2" style="width:90%; background: #fbfbfb;">
                                <div style="justify-content:space-between; display: flex;">
                                    <small>
                                        <i class="fa fa-user"></i> {{review.user}} &nbsp;|&nbsp;
                                        <!-- rated: {{review.rate}}  -->
                                        <i class="fa fa-clock-o colored"></i> {{review.date_created}}
                                    </small> 
                                    <small style="justify-content:right; display: flex; color:rgb(138, 138, 138)">
                                        <span class="colored fa fa-star{% if review.rate < 1 %}-o empty {% endif %} "></span>
                                        <span class="colored fa fa-star{% if review.rate < 2 %}-o empty {% endif %} "></span>
                                        <span class="colored fa fa-star{% if review.rate < 3 %}-o empty {% endif %} "></span>
                                        <span class="colored fa fa-star{% if review.rate < 4 %}-o empty {% endif %} "></span>
                                        <span class="colored fa fa-star{% if review.rate < 5 %}-o empty {% endif %} "></span>
                                    </small>
                                </div><hr style="margin-top: 2px; margin-bottom: 5px;">
                                <p><span style="color: #888;font-style: italic; font:15px calibri;">{{review.review}}</span></p>
                            </div>
                            {% endfor %}
                            
                        </div>
        
                        <div class="col-sm-5">
                            <div class="container">
                                <form action="" method="post" class="form-group  ratingForm" style=''>
                                    {% csrf_token %}
                                    <h5 class="text-dark" style="font-weight: 600;">ADD YOUR REVIEW</h5>
                                    {% for message in messages %}
                                        <p class="alert alert-warning p-1"><i class='fa fa-warning'></i> {{ message }}</p>
                                        {{ review_form.errors }}
                                    {% endfor %}
                                    <input type="hidden" value="{{review_form.product.id}}" id="id_product" name="product"  class="form-control">
                                    <span class="form-group">
                                        <!-- <label for="name">Name</label><br> -->
                                        <input type="hidden" name="user" value="{{request.user}}"  id="id_user" class="form-control">
                                    </span>
                                    <span class="form-group">
                                        <!-- <label for="email">Email</label><br> -->
                                        <input type="hidden" name="user_email" id="id_user_email" value="{{ request.user.email}}"  class="form-control">
                                    </span>
                                    <div class="form-group">
                                        <div class="input-rating">
                                            <div class="stars table-bordered p-2 text-secondary" >
                                                Your Rating: &nbsp;&nbsp;
                                                <input class='fa fa-star colored' type="radio" name="rate" id="star1" value="1"><label for="star1"></label>
                                                <input class='fa fa-star colored' type="radio" name="rate" id="star2" value="2"><label for="star2"></label>
                                                <input class='fa fa-star colored' type="radio" name="rate" id="star3" value="3"><label for="star3"></label>
                                                <input class='fa fa-star colored' type="radio" name="rate" id="star4" value="4"><label for="star4"></label>
                                                <input class='fa fa-star colored' type="radio" name="rate" id="star5" value="5"><label for="star5"></label>
                                            </div>
                                        </div>
                                    </div>
                                    <span class="form-group">
                                        <textarea name="review" id="id_review" cols="20" rows="2" class="form-control" placeholder="Your Review"></textarea>
                                    </span><br>
                                    {% if user.is_authenticated %}
                                    <button class="btn btn-warning btn-block">Submit</button>
                                    {% else %}
                                    To Add your review <a href="{% url 'login' %}" class="">Login is required</a>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
</div>

<script>
    var product = "{{ selected_product.id }}";
    document.getElementById('id_product').value = product;
</script>



{% endblock %}